// <auto-generated />
using System;
using System.Text.Json;
using EventPlug.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventPlug.Api.Data.Migrations
{
    [DbContext(typeof(EventPlugDbContext))]
    [Migration("20260918112631_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.AIStructuringDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("RawInputText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_input_text");

                    b.Property<JsonDocument>("StructuredOutput")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("structured_output");

                    b.HasKey("Id")
                        .HasName("pk_ai_structuring_drafts");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_ai_structuring_drafts_created_by");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_ai_structuring_drafts_event_id");

                    b.ToTable("ai_structuring_drafts", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_approvals");

                    b.HasIndex("ApproverId")
                        .HasDatabaseName("ix_approvals_approver_id");

                    b.HasIndex("ExpenseId")
                        .HasDatabaseName("ix_approvals_expense_id");

                    b.HasIndex("RequestedBy")
                        .HasDatabaseName("ix_approvals_requested_by");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_approvals_team_id");

                    b.ToTable("approvals", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.ApprovalAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("ApprovalId")
                        .HasColumnType("uuid")
                        .HasColumnName("approval_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_approval_audit_entries");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_approval_audit_entries_actor_id");

                    b.HasIndex("ApprovalId")
                        .HasDatabaseName("ix_approval_audit_entries_approval_id");

                    b.ToTable("approval_audit_entries", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.BudgetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AllocatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("allocated_amount");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_type");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.HasKey("Id")
                        .HasName("pk_budget_categories");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_budget_categories_event_id");

                    b.ToTable("budget_categories", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BudgetBand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("budget_band");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<int?>("GuestCountEstimate")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count_estimate");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("location");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StyleNotes")
                        .HasColumnType("text")
                        .HasColumnName("style_notes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_events_created_by");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_events_org_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.EventTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApproverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_user_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsOwningTeam")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owning_team");

                    b.Property<string>("SplitMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("split_method");

                    b.Property<decimal?>("SplitValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("split_value");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_event_teams");

                    b.HasIndex("ApproverUserId")
                        .HasDatabaseName("ix_event_teams_approver_user_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_event_teams_team_id");

                    b.HasIndex("EventId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_teams_event_id_team_id");

                    b.ToTable("event_teams", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BudgetCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("BudgetCategoryId")
                        .HasDatabaseName("ix_expenses_budget_category_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_expenses_created_by");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_expenses_vendor_id");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.ExpenseTeamSplit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<decimal>("PortionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("portion_amount");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_expense_team_splits");

                    b.HasIndex("ExpenseId")
                        .HasDatabaseName("ix_expense_team_splits_expense_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_expense_team_splits_team_id");

                    b.ToTable("expense_team_splits", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("access_notes");

                    b.Property<string>("DietaryNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("dietary_notes");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RsvpStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rsvp_status");

                    b.HasKey("Id")
                        .HasName("pk_guests");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_guests_event_id");

                    b.ToTable("guests", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("BillingCycleStart")
                        .HasColumnType("date")
                        .HasColumnName("billing_cycle_start");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subscription_tier");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.QuoteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<JsonDocument>("BriefSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("brief_snapshot");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("SentToEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("sent_to_email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("VendorEventLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_event_link_id");

                    b.HasKey("Id")
                        .HasName("pk_quote_requests");

                    b.HasIndex("VendorEventLinkId")
                        .HasDatabaseName("ix_quote_requests_vendor_event_link_id");

                    b.ToTable("quote_requests", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.RunSheetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_run_sheet_items");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_run_sheet_items_event_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_run_sheet_items_owner_user_id");

                    b.ToTable("run_sheet_items", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_teams_org_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.TeamMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("team_role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_team_memberships");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_team_memberships_team_id");

                    b.HasIndex("UserId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_team_memberships_user_id_team_id");

                    b.ToTable("team_memberships", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("OrgRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("org_role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("OrgId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_org_id_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.HasKey("Id")
                        .HasName("pk_vendors");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_vendors_org_id");

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.VendorEventLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_vendor_event_links");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_vendor_event_links_event_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_vendor_event_links_vendor_id");

                    b.ToTable("vendor_event_links", (string)null);
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.AIStructuringDraft", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.User", "CreatedByUser")
                        .WithMany("AiStructuringDrafts")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ai_structuring_drafts_users_created_by");

                    b.HasOne("EventPlug.Api.Domain.Entities.Event", "Event")
                        .WithMany("AiStructuringDrafts")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ai_structuring_drafts_events_event_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Approval", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.User", "ApproverUser")
                        .WithMany("DecidingApprovals")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_users_approver_id");

                    b.HasOne("EventPlug.Api.Domain.Entities.Expense", "Expense")
                        .WithMany("Approvals")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_expenses_expense_id");

                    b.HasOne("EventPlug.Api.Domain.Entities.User", "RequestedByUser")
                        .WithMany("RequestedApprovals")
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_users_requested_by");

                    b.HasOne("EventPlug.Api.Domain.Entities.Team", "Team")
                        .WithMany("Approvals")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_teams_team_id");

                    b.Navigation("ApproverUser");

                    b.Navigation("Expense");

                    b.Navigation("RequestedByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.ApprovalAuditEntry", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.User", "Actor")
                        .WithMany("ApprovalAuditEntries")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approval_audit_entries_users_actor_id");

                    b.HasOne("EventPlug.Api.Domain.Entities.Approval", "Approval")
                        .WithMany("AuditEntries")
                        .HasForeignKey("ApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_audit_entries_approvals_approval_id");

                    b.Navigation("Actor");

                    b.Navigation("Approval");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.BudgetCategory", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.Event", "Event")
                        .WithMany("BudgetCategories")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_categories_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Event", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_users_created_by");

                    b.HasOne("EventPlug.Api.Domain.Entities.Organization", "Organization")
                        .WithMany("Events")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_organizations_org_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.EventTeam", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.User", "ApproverUser")
                        .WithMany("EventTeamApprovals")
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_teams_users_approver_user_id");

                    b.HasOne("EventPlug.Api.Domain.Entities.Event", "Event")
                        .WithMany("EventTeams")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_teams_events_event_id");

                    b.HasOne("EventPlug.Api.Domain.Entities.Team", "Team")
                        .WithMany("EventTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_teams_teams_team_id");

                    b.Navigation("ApproverUser");

                    b.Navigation("Event");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Expense", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.BudgetCategory", "BudgetCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("BudgetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_budget_categories_budget_category_id");

                    b.HasOne("EventPlug.Api.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedExpenses")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_users_created_by");

                    b.HasOne("EventPlug.Api.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Expenses")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_expenses_vendors_vendor_id");

                    b.Navigation("BudgetCategory");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.ExpenseTeamSplit", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.Expense", "Expense")
                        .WithMany("ExpenseTeamSplits")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_team_splits_expenses_expense_id");

                    b.HasOne("EventPlug.Api.Domain.Entities.Team", "Team")
                        .WithMany("ExpenseTeamSplits")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_team_splits_teams_team_id");

                    b.Navigation("Expense");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Guest", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.Event", "Event")
                        .WithMany("Guests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guests_events_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.QuoteRequest", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.VendorEventLink", "VendorEventLink")
                        .WithMany("QuoteRequests")
                        .HasForeignKey("VendorEventLinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quote_requests_vendor_event_links_vendor_event_link_id");

                    b.Navigation("VendorEventLink");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.RunSheetItem", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.Event", "Event")
                        .WithMany("RunSheetItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_sheet_items_events_event_id");

                    b.HasOne("EventPlug.Api.Domain.Entities.User", "OwnerUser")
                        .WithMany("RunSheetItems")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_run_sheet_items_users_owner_user_id");

                    b.Navigation("Event");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Team", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teams_organizations_org_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.TeamMembership", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.Team", "Team")
                        .WithMany("Memberships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_memberships_teams_team_id");

                    b.HasOne("EventPlug.Api.Domain.Entities.User", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_memberships_users_user_id");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.User", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_organizations_org_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Vendor", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.Organization", "Organization")
                        .WithMany("Vendors")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendors_organizations_org_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.VendorEventLink", b =>
                {
                    b.HasOne("EventPlug.Api.Domain.Entities.Event", "Event")
                        .WithMany("VendorEventLinks")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_event_links_events_event_id");

                    b.HasOne("EventPlug.Api.Domain.Entities.Vendor", "Vendor")
                        .WithMany("VendorEventLinks")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_event_links_vendors_vendor_id");

                    b.Navigation("Event");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Approval", b =>
                {
                    b.Navigation("AuditEntries");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.BudgetCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Event", b =>
                {
                    b.Navigation("AiStructuringDrafts");

                    b.Navigation("BudgetCategories");

                    b.Navigation("EventTeams");

                    b.Navigation("Guests");

                    b.Navigation("RunSheetItems");

                    b.Navigation("VendorEventLinks");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Expense", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("ExpenseTeamSplits");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Teams");

                    b.Navigation("Users");

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Team", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("EventTeams");

                    b.Navigation("ExpenseTeamSplits");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("AiStructuringDrafts");

                    b.Navigation("ApprovalAuditEntries");

                    b.Navigation("CreatedEvents");

                    b.Navigation("CreatedExpenses");

                    b.Navigation("DecidingApprovals");

                    b.Navigation("EventTeamApprovals");

                    b.Navigation("RequestedApprovals");

                    b.Navigation("RunSheetItems");

                    b.Navigation("TeamMemberships");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("VendorEventLinks");
                });

            modelBuilder.Entity("EventPlug.Api.Domain.Entities.VendorEventLink", b =>
                {
                    b.Navigation("QuoteRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
